"""AdiTradeX V5.0 - Milestone 6.1B-1 Scoring Configuration"""

TREND_WEIGHT = 25
MOMENTUM_WEIGHT = 15
STRUCTURE_WEIGHT = 15
VWAP_WEIGHT = 15
OPTION_CHAIN_WEIGHT = 20
LIQUIDITY_WEIGHT = 10

TOTAL_WEIGHT = (
    TREND_WEIGHT + MOMENTUM_WEIGHT + STRUCTURE_WEIGHT +
    VWAP_WEIGHT + OPTION_CHAIN_WEIGHT + LIQUIDITY_WEIGHT
)

GRADE_A_PLUS = 95
GRADE_A = 90
GRADE_B = 80
GRADE_C = 70

QUALITY_INSTITUTIONAL = 90
QUALITY_HIGH = 80
QUALITY_WATCHLIST = 70
QUALITY_WEAK = 60

DEFAULT_SCORE = 50
MIN_SCORE = 0
MAX_SCORE = 100

SCORING_ENGINE_VERSION = "6.1B-1"
ENGINE_NAME = "Institutional Score Core"
